name: Run ESLint on Pull Requests

on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14 # or any version higher than 14

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        uses: eslint/github-action@v0
        with:
          args: --fix
